import os
import logging
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)

SEVERITY_TO_PRIORITY = {
    "critical": "Highest",
    "high":     "High",
    "medium":   "Medium",
    "low":      "Low",
}

CATEGORY_TO_LABEL = {
    "code_quality":  "tech-debt-code",
    "security":      "tech-debt-security",
    "documentation": "tech-debt-docs",
    "dependency":    "tech-debt-deps",
    "test_debt":     "tech-debt-tests",
}


class JiraClient:
    """Creates Jira tickets for tech debt items."""

    def __init__(self):
        self.server = os.getenv("JIRA_SERVER", "")
        self.email = os.getenv("JIRA_EMAIL", "")
        self.token = os.getenv("JIRA_API_TOKEN", "")
        self.project = os.getenv("JIRA_PROJECT_KEY", "TD")
        self._jira = None

    @property
    def jira(self):
        if not self._jira:
            from jira import JIRA
            self._jira = JIRA(
                server=self.server,
                basic_auth=(self.email, self.token)
            )
        return self._jira

    def is_configured(self) -> bool:
        return bool(
            self.server and self.email and self.token
            and self.server != "https://yourcompany.atlassian.net"
        )

    def create_tickets_for_analysis(
        self,
        result: dict,
        max_tickets: int = 10,
        min_severity: str = "medium",
    ) -> dict:
        """
        Create Jira tickets for top debt items.
        Returns summary of created/failed tickets.
        """
        if not self.is_configured():
            return {"ok": False, "error": "Jira not configured"}

        analysis = result.get("raw_analysis", {})
        if not analysis:
            analysis = {
                "debt_items": result.get("debt_items", []),
                "total_cost_usd": result.get("total_cost_usd", 0),
                "debt_score": result.get("debt_score", 0),
                "total_remediation_hours": result.get("total_remediation_hours", 0),
            }
        repo_url = result.get("github_url", "Unknown")
        debt_items = analysis.get("debt_items", [])

        # Filter by severity
        severity_order = ["critical", "high", "medium", "low"]
        min_idx = severity_order.index(min_severity)
        eligible = [
            item for item in debt_items
            if severity_order.index(
                (item.get("severity") or "low").lower()
            ) <= min_idx
        ]

        # Sort by cost desc
        eligible = sorted(
            eligible,
            key=lambda x: x.get("cost_usd", 0),
            reverse=True
        )[:max_tickets]

        created = []
        failed = []

        for item in eligible:
            try:
                ticket = self._create_ticket(
                    item, result, analysis, repo_url
                )
                created.append({
                    "key": ticket.key,
                    "url": f"{self.server}/browse/{ticket.key}",
                    "file": item.get("file", ""),
                    "cost": item.get("cost_usd", 0),
                })
                logger.info(f"Created Jira ticket: {ticket.key}")
            except Exception as e:
                failed.append({
                    "file": item.get("file", ""),
                    "error": str(e)
                })
                logger.error(
                    f"Failed to create ticket for "
                    f"{item.get('file','?')}: {e}"
                )

        return {
            "ok": True,
            "created": created,
            "failed": failed,
            "total_created": len(created),
            "total_failed": len(failed),
        }

    def _create_epic(self,
                      result: dict,
                      analysis: dict) -> str | None:
        """Create an Epic to group all debt tickets."""
        try:
            repo = result.get("github_url", "Unknown")
            repo_name = repo.split("/")[-1] if "/" in repo else repo
            cost = analysis.get("total_cost_usd", 0)
            score = analysis.get("debt_score", 0)

            summary = (
                f"[Tech Debt] {repo_name} — "
                f"${cost:,.0f} total debt (score: {score:.1f}/10)"
            )

            description = (
                f"*Repository:* {repo}\n\n"
                f"*Total Cost:* ${cost:,.0f}\n"
                f"*Debt Score:* {score:.1f}/10\n"
                f"*Remediation Hours:* "
                f"{analysis.get('total_remediation_hours', 0):.0f}h\n\n"
                f"*Executive Summary:*\n"
                f"{result.get('executive_summary', 'N/A')}\n\n"
                f"_Generated by Tech Debt Quantifier_"
            )

            epic = self.jira.create_issue(fields={
                "project": {"key": self.project},
                "summary": summary,
                "description": description,
                "issuetype": {"name": "Epic"},
                "labels": ["tech-debt", "automated"],
            })
            return epic.key
        except Exception as e:
            logger.warning(f"Could not create Epic: {e}")
            return None

    def _create_ticket(
        self,
        item: dict,
        result: dict,
        analysis: dict,
        repo_url: str,
    ):
        """Create a single Story/Task ticket for a debt item."""
        import re

        file_path = str(item.get("file", "unknown"))
        # Strip temp path prefix
        file_path = re.sub(
            r'^/tmp/repos/[^/]+/', '', file_path
        )
        file_path = re.sub(r':\?$|:\d+$', '', file_path)

        category = (
            item.get("category") or "code_quality"
        ).replace("_", " ").title()
        severity = (item.get("severity") or "medium").lower()
        cost = item.get("cost_usd", 0)
        hours = (item.get("adjusted_minutes") or 0) / 60
        complexity = item.get("complexity", "N/A")
        function_name = item.get("function", "")

        priority = SEVERITY_TO_PRIORITY.get(severity, "Medium")
        label = CATEGORY_TO_LABEL.get(
            item.get("category", "code_quality"),
            "tech-debt"
        )

        summary = (
            f"[{category}] {file_path}"
            + (f" — {function_name}" if function_name else "")
        )
        if len(summary) > 255:
            summary = summary[:252] + "..."

        description = (
            f"*Tech Debt Item Details*\n\n"
            f"*File:* +{file_path}+\n"
            f"*Function:* {function_name or 'N/A'}\n"
            f"*Category:* {category}\n"
            f"*Severity:* {severity.upper()}\n\n"
            f"*Estimated Cost:* ${cost:,.0f}\n"
            f"*Remediation Hours:* {hours:.1f}h\n"
            f"*Complexity Score:* {complexity}\n\n"
            f"*Repository:* {repo_url}\n\n"
            f"_Generated by Tech Debt Quantifier_"
        )

        fields = {
            "project": {"key": self.project},
            "summary": summary,
            "description": description,
            "issuetype": {"name": "Task"},
            "priority": {"name": priority},
            "labels": [label, "tech-debt", "automated"],
        }

        return self.jira.create_issue(fields=fields)